app:
  name: "go_web_template"
  mode: "debug"
  port: 8080
log:
  level: "debug"
  filename: "go_web_template.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "mysql_demo"
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100